name: CI/CD

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: used-car-project-bucket
  CODE_DEPLOY_APPLICATION_NAME: CODE-DEPLOY-USEDCAR
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: CODE-DEPLOY-GROUP

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Generate application.yml from Secrets
        run: |
          mkdir -p src/main/resources
          echo "admin.adminId=${{ secrets.ADMIN_ID }}" > src/main/resources/application.yml
          echo "admin.password=${{ secrets.ADMIN_PASSWORD }}" >> src/main/resources/application.yml
          echo "admin.adminEmail=${{ secrets.ADMIN_EMAIL }}" >> src/main/resources/application.yml
          echo "admin.adminPhone=${{ secrets.ADMIN_PHONE }}" >> src/main/resources/application.yml
          echo "admin.adminName=${{ secrets.ADMIN_NAME }}" >> src/main/resources/application.yml
          echo "spring.datasource.url=${{ secrets.DB_ENDPOINT }}" >> src/main/resources/application.yml
          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> src/main/resources/application.yml
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> src/main/resources/application.yml
          echo "jwt.secret_key=${{ secrets.JWT_SECRET_KEY }}" >> src/main/resources/application.yml
          echo "aws.access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> src/main/resources/application.yml
          echo "aws.secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> src/main/resources/application.yml
          echo "aws.region=${{ secrets.AWS_REGION }}" >> src/main/resources/application.yml

      - name: Build with Gradle
        run: ./gradlew build

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
