name: Java CI/CD with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # 도커 허브 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 도커 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/used-car-app .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/used-car-app

      # EC2 접속 및 컨테이너 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. 기존 컨테이너 및 네트워크 정리 (nginx-proxy 포함)
            docker stop spring-app mysql-db nginx-proxy || true
            docker rm spring-app mysql-db nginx-proxy || true
            docker network rm used-car-net || true

            # 2. 전용 네트워크 생성
            docker network create used-car-net

            # 3. MySQL 실행 (네트워크 연결)
            docker run -d --name mysql-db \
              --network used-car-net \
              -e MYSQL_ROOT_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              -e MYSQL_DATABASE='usedcar_db' \
              mysql:8.0

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/used-car-app
            docker run -d --name spring-app \
              --network used-car-net \
              -e DB_URL='jdbc:mysql://mysql-db:3306/usedcar_db' \
              -e DB_USERNAME='root' \
              -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              -e AWS_ACCESS_KEY='${{ secrets.AWS_ACCESS_KEY }}' \
              -e AWS_SECRET_KEY='${{ secrets.AWS_SECRET_KEY }}' \
              -e AWS_REGION='${{ secrets.AWS_REGION }}' \
              -e AWS_S3_BUCKET_NAME='${{ secrets.AWS_S3_BUCKET_NAME }}' \
              -e JWT_ISSUER='${{ secrets.JWT_ISSUER }}' \
              -e JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}' \
              -e ADMIN_ID='${{ secrets.ADMIN_ID }}' \
              -e ADMIN_PASSWORD='${{ secrets.ADMIN_PASSWORD }}' \
              -e ADMIN_EMAIL='${{ secrets.ADMIN_EMAIL }}' \
              -e ADMIN_PHONE='${{ secrets.ADMIN_PHONE }}' \
              -e ADMIN_NAME='${{ secrets.ADMIN_NAME }}' \
              ${{ secrets.DOCKERHUB_USERNAME }}/used-car-app

            docker run -d --name nginx-proxy \
              -p 80:80 \
              --network used-car-net \
              -v /home/ubuntu/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro \
              nginx:latest